### ISSUE TITLE
ModuleNotFoundError: No module named 'extrude_tensor_ext

### ISSUE THREAD

**Issue by hujinhong** [hzxie/CityDreamer#23]
ty) user@user-System-Product-Name:~/hjh/city-dreamer$ python demo/run.py
Traceback (most recent call last):
  File "demo/run.py", line 29, in <module>
    import scripts.inference as inference
  File "/home/user/hjh/city-dreamer/demo/../scripts/inference.py", line 31, in <module>
    import extensions.extrude_tensor
  File "/home/user/hjh/city-dreamer/demo/../extensions/extrude_tensor/__init__.py", line 12, in <module>
    import extrude_tensor_ext
ModuleNotFoundError: No module named 'extrude_tensor_ext

**Comment by DuXikb** [comment]
do you solve this problem？could you teach me？thanks！

**Comment by DuXikb** [comment]
do you solve this problem？could you teach me？thanks！

**Comment by hzxie** [comment]
@DuXikb 

As mentioned in README, please install Python dependencies as follows.

```
git clone https://github.com/hzxie/city-dreamer
cd city-dreamer
CITY_DREAMER_HOME=`pwd`
pip install -r requirements.txt
```
